#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-rncl
Version  : 0.8.7
Release  : 50
URL      : https://cran.r-project.org/src/contrib/rncl_0.8.7.tar.gz
Source0  : https://cran.r-project.org/src/contrib/rncl_0.8.7.tar.gz
Summary  : An Interface to the Nexus Class Library
Group    : Development/Tools
License  : BSD-2-Clause
Requires: R-rncl-lib = %{version}-%{release}
Requires: R-Rcpp
Requires: R-progress
BuildRequires : R-Rcpp
BuildRequires : R-ape
BuildRequires : R-progress
BuildRequires : buildreq-R

%description
of NEXUS, Newick and other phylogenetic tree file formats. It provides
    elements of the file that can be used to build phylogenetic objects
    such as ape's 'phylo' or phylobase's 'phylo4(d)'. This functionality
    is demonstrated with 'read_newick_phylo()' and 'read_nexus_phylo()'.

%package lib
Summary: lib components for the R-rncl package.
Group: Libraries

%description lib
lib components for the R-rncl package.


%prep
%setup -q -n rncl
pushd ..
cp -a rncl buildavx2
popd
pushd ..
cp -a rncl buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1737157478

%install
export SOURCE_DATE_EPOCH=1737157478
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/rncl/DESCRIPTION
/usr/lib64/R/library/rncl/INDEX
/usr/lib64/R/library/rncl/LICENSE
/usr/lib64/R/library/rncl/Meta/Rd.rds
/usr/lib64/R/library/rncl/Meta/features.rds
/usr/lib64/R/library/rncl/Meta/hsearch.rds
/usr/lib64/R/library/rncl/Meta/links.rds
/usr/lib64/R/library/rncl/Meta/nsInfo.rds
/usr/lib64/R/library/rncl/Meta/package.rds
/usr/lib64/R/library/rncl/NAMESPACE
/usr/lib64/R/library/rncl/NEWS.md
/usr/lib64/R/library/rncl/R/rncl
/usr/lib64/R/library/rncl/R/rncl.rdb
/usr/lib64/R/library/rncl/R/rncl.rdx
/usr/lib64/R/library/rncl/help/AnIndex
/usr/lib64/R/library/rncl/help/aliases.rds
/usr/lib64/R/library/rncl/help/paths.rds
/usr/lib64/R/library/rncl/help/rncl.rdb
/usr/lib64/R/library/rncl/help/rncl.rdx
/usr/lib64/R/library/rncl/html/00Index.html
/usr/lib64/R/library/rncl/html/R.css
/usr/lib64/R/library/rncl/newick_bad/Gudrun.nex
/usr/lib64/R/library/rncl/newick_bad/bad_newick.tre
/usr/lib64/R/library/rncl/newick_good/Gudrun.tre
/usr/lib64/R/library/rncl/newick_good/missing_edge_lengths.tre
/usr/lib64/R/library/rncl/newick_good/simpleTree.tre
/usr/lib64/R/library/rncl/newick_good/singleton_tree.tre
/usr/lib64/R/library/rncl/newick_good/singleton_with_edge_length.tre
/usr/lib64/R/library/rncl/newick_good/test_sing.tre
/usr/lib64/R/library/rncl/newick_good/tree1.tre
/usr/lib64/R/library/rncl/newick_good/tree2.tre
/usr/lib64/R/library/rncl/nexusfiles/MultiLineTrees.nex
/usr/lib64/R/library/rncl/nexusfiles/badnex.nex
/usr/lib64/R/library/rncl/nexusfiles/co1.nex
/usr/lib64/R/library/rncl/nexusfiles/multiLines.rds
/usr/lib64/R/library/rncl/nexusfiles/newick.tre
/usr/lib64/R/library/rncl/nexusfiles/test_empty.nex
/usr/lib64/R/library/rncl/nexusfiles/test_subset_taxa.nex
/usr/lib64/R/library/rncl/nexusfiles/test_underscores.nex
/usr/lib64/R/library/rncl/nexusfiles/treeWithDiscreteData.nex
/usr/lib64/R/library/rncl/nexusfiles/treeWithUnderscoreLabels.nex
/usr/lib64/R/library/rncl/tests/test-all.R
/usr/lib64/R/library/rncl/tests/testthat/test.badnex.R
/usr/lib64/R/library/rncl/tests/testthat/test.rncl.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/rncl/libs/rncl.so
/V4/usr/lib64/R/library/rncl/libs/rncl.so
/usr/lib64/R/library/rncl/libs/rncl.so
